import * as THREE from 'three';

const { gsap, ScrollTrigger, SplitText, Lenis } = window;
gsap.registerPlugin(ScrollTrigger, SplitText);

/* ------------------------------------------------------------------
   Components. `id` matches a track in data/tracks.json (generated by
   tools/track.py). `off` is the callout end point relative to the anchor,
   in screen-plane units [x, y, z toward camera].
------------------------------------------------------------------ */
const LABELS = [
  {
    id: 'flare', name: 'Flare stack', kicker: 'Pressure relief', chapter: 1, jump: 22,
    off: [-0.2, -0.65, 0.6],
    desc: 'When a unit trips or pressure rises beyond safe limits, excess hydrocarbon gas is piped here and burned at the tip rather than released unburned. A small pilot flame stays lit at all times so the stack is ready to take load.',
    specs: [['Height', '60–120 m'], ['Tip temperature', 'Above 1,000 °C'], ['Combustion efficiency', 'Over 98 %'], ['Pilot flame', 'Continuous']],
    flow: 'Relief valves across the plant, via a shared flare header and knock-out drum.',
  },
  {
    id: 'column', name: 'Distillation column', kicker: 'Crude distillation unit', chapter: 1, jump: 30,
    off: [1.3, 0.62, 0.8],
    desc: 'Heated crude enters near the base as a mix of vapour and liquid. Vapour rises through trays and cools as it climbs. Each fraction condenses at the height that matches its boiling point and is drawn off as a side stream.',
    specs: [['Feed temperature', '350–400 °C'], ['Trays', '30–50'], ['Pressure', 'About 1–1.5 bar'], ['Product streams', '5–7']],
    flow: 'Fed by the fired heater. Sends naphtha, kerosene and diesel on to the hydrotreaters, and residue to the conversion units.',
  },
  {
    id: 'jetty', name: 'Breakwater', kicker: 'Marine', chapter: 1, jump: 8,
    off: [0.25, 0.95, 0.5],
    desc: 'A rock breakwater shelters the berths from open-sea swell so tankers can moor and stay connected to the loading arms in poor weather. Pipelines run along it between the berths and the tank farm.',
    specs: [['Water depth at berth', '15–25 m'], ['Vessel size', 'Aframax to VLCC'], ['Loading arms', '4–8 per berth']],
    flow: 'Tanker berths and the shore pipelines to storage.',
  },
  {
    id: 'tanker', name: 'Crude tanker', kicker: 'Marine terminal', chapter: 1, also: [3], jump: 176,
    off: [0.95, 0.72, 0.6],
    desc: 'Crude arrives by sea and most finished products leave the same way. A large carrier can discharge its full cargo in around a day and a half, pumped ashore into the crude tanks.',
    specs: [['Deadweight', '100,000–320,000 t'], ['Cargo', '0.7–2 million barrels'], ['Discharge time', '24–36 h']],
    flow: 'Unloads to the crude tanks; loads gasoline, diesel and jet fuel from product storage.',
  },
  {
    id: 'heater', name: 'Fired heater', kicker: 'Furnace', chapter: 2, jump: 92,
    off: [-1.55, -0.3, 0.7],
    desc: 'Burners fire into a box lined with steel tubes. Oil flows through the tubes and leaves hot enough to partly vaporise before it enters the column or a reactor. Heaters are the largest energy users on the site.',
    specs: [['Outlet temperature', '370–420 °C'], ['Heat duty', '50–150 MW'], ['Fuel', 'Refinery gas or oil'], ['Efficiency', '85–92 %']],
    flow: 'Directly upstream of the distillation column and the reactors.',
  },
  {
    id: 'reactor', name: 'Hydrotreater reactors', kicker: 'Catalytic desulphurisation', chapter: 2, jump: 100,
    off: [1.35, 0.5, 0.8],
    desc: 'Thick-walled vessels filled with catalyst beds. Hot oil and hydrogen flow down through the beds, where sulphur and nitrogen compounds are removed so the fuel meets road and aviation specifications.',
    specs: [['Temperature', '300–400 °C'], ['Pressure', '30–130 bar'], ['Sulphur in product', 'Under 10 ppm'], ['Catalyst life', '2–4 years']],
    flow: 'Takes side streams from the distillation column; hydrogen comes from the reformer.',
  },
  {
    id: 'piperack', name: 'Main pipe rack', kicker: 'Utilities', chapter: 3, jump: 172,
    off: [-1.2, -0.55, 0.6],
    desc: 'A steel structure carrying dozens of pipes side by side: crude, intermediate and finished products, plus steam, cooling water, nitrogen and instrument air. It links every unit to storage.',
    specs: [['Lines carried', '40–120'], ['Levels', '2–4'], ['Pipe sizes', '2–48 in']],
    flow: 'Process units, tank farm and marine terminal.',
  },
  {
    id: 'tankfarm', name: 'Floating-roof tanks', kicker: 'Storage', chapter: 3, jump: 182,
    off: [1.05, 0.7, 0.6],
    desc: 'The roof of each tank floats on the liquid and moves with the level, leaving almost no vapour space and cutting evaporation losses. The spiral stair leads to a ladder that follows the roof down. White paint keeps the contents cooler.',
    specs: [['Capacity per tank', '50,000–160,000 m³'], ['Diameter', '40–90 m'], ['Roof', 'External floating']],
    flow: 'Holds crude before processing and finished products before shipping.',
  },
  {
    id: 'units', name: 'Conversion units', kicker: 'Cracking and reforming', chapter: 3, jump: 178,
    off: [-1.25, -0.2, 0.6],
    desc: 'The row of tall columns on the horizon. Catalytic crackers break heavy residue into lighter, more valuable products. Reformers turn naphtha into high-octane gasoline blendstock and produce hydrogen as a by-product.',
    specs: [['Cracker reactor', '500–540 °C'], ['Reformer', 'About 500 °C'], ['Main products', 'Gasoline, LPG, hydrogen']],
    flow: 'Takes residue from distillation; supplies hydrogen to the hydrotreaters.',
  },
];
LABELS.forEach((l, i) => { l.idx = String(i + 1).padStart(2, '0'); });

const FRAME_COUNT = 192;
const PW = 16, PH = 9, CURVE_R = 26;
const mqMobile = matchMedia('(max-width: 860px)');
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
const quality = innerWidth < 900 ? 'sd' : 'hd';

const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const clamp = (v, a, b) => Math.min(b, Math.max(a, v));
const lerp = (a, b, t) => a + (b - a) * t;
const curveZ = (x) => -(x * x) / (2 * CURVE_R);
const byId = (id) => LABELS.find((l) => l.id === id);

/* ------------------------------------------------------------------ Loading */
const images = new Array(FRAME_COUNT);
let loadedCount = 0;
function loadFrame(i) {
  return new Promise((resolve) => {
    const img = new Image();
    img.decoding = 'async';
    const done = () => {
      loadedCount++;
      $('#loader-n').textContent = loadedCount;
      $('#loader-fill').style.width = `${(loadedCount / FRAME_COUNT) * 100}%`;
      resolve();
    };
    img.onload = () => { images[i] = img; done(); };
    img.onerror = done;
    img.src = `frames/${quality}/f_${String(i + 1).padStart(3, '0')}.webp`;
  });
}
async function loadAll() {
  let next = 0;
  const worker = async () => { while (next < FRAME_COUNT) await loadFrame(next++); };
  await Promise.all(Array.from({ length: 10 }, worker));
}

function smoothTrack(arr, win = 2) {
  return arr.map((p, i) => {
    if (!p) return null;
    let sx = 0, sy = 0, n = 0;
    for (let k = -win; k <= win; k++) {
      const q = arr[i + k];
      if (q) { sx += q[0]; sy += q[1]; n++; }
    }
    return [sx / n, sy / n];
  });
}

/* ------------------------------------------------------------------ Three.js */
const renderer = new THREE.WebGLRenderer({ canvas: $('#stage'), antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
const scene = new THREE.Scene();
scene.background = new THREE.Color(0x0b0b0c);
const camera = new THREE.PerspectiveCamera(30, innerWidth / innerHeight, 0.1, 200);
let baseDist = 15;

const rig = new THREE.Group();
scene.add(rig);

const frameTex = new THREE.Texture();
frameTex.minFilter = frameTex.magFilter = THREE.LinearFilter;
frameTex.generateMipmaps = false;
frameTex.colorSpace = THREE.NoColorSpace;

// The footage sits on a gently curved screen so mouse tilt reads as real depth
const planeGeo = new THREE.PlaneGeometry(PW, PH, 96, 54);
{
  const pos = planeGeo.attributes.position;
  for (let i = 0; i < pos.count; i++) pos.setZ(i, curveZ(pos.getX(i)));
}
const planeMat = new THREE.ShaderMaterial({
  uniforms: { uTex: { value: frameTex }, uVel: { value: 0 }, uFade: { value: 0 }, uDim: { value: 0 } },
  vertexShader: /* glsl */`
    varying vec2 vUv;
    void main() { vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }
  `,
  fragmentShader: /* glsl */`
    uniform sampler2D uTex; uniform float uVel, uFade, uDim;
    varying vec2 vUv;
    void main() {
      vec2 c = vUv - 0.5;
      float d = length(c);
      vec2 shift = c * d * uVel * 0.02;
      vec3 col = vec3(texture2D(uTex, vUv + shift).r, texture2D(uTex, vUv).g, texture2D(uTex, vUv - shift).b);
      col = mix(col, col * col * (3.0 - 2.0 * col), 0.15);
      col *= mix(0.45, 1.0, smoothstep(0.85, 0.25, d));
      col *= uFade * (1.0 - uDim * 0.6);
      gl_FragColor = vec4(col, 1.0);
    }
  `,
});
const plane = new THREE.Mesh(planeGeo, planeMat);
rig.add(plane);

/* 3D markers: a ring lying in perspective, a pulse ring and a leader line per component */
const ACCENT = new THREE.Color('#f0a24a');
const INK = new THREE.Color('#f2efe9');
const ringGeo = new THREE.RingGeometry(0.1, 0.116, 64);
const coreGeo = new THREE.CircleGeometry(0.026, 24);
const markMat = (color) => new THREE.MeshBasicMaterial({ color, transparent: true, depthTest: false, depthWrite: false, side: THREE.DoubleSide });

const tagLayer = $('#tags');
LABELS.forEach((l) => {
  const g = new THREE.Group();
  const ring = new THREE.Mesh(ringGeo, markMat(ACCENT));
  const ping = new THREE.Mesh(ringGeo, markMat(ACCENT));
  const core = new THREE.Mesh(coreGeo, markMat(INK));
  ring.rotation.x = ping.rotation.x = -1.1;
  const end = new THREE.Vector3(...l.off);
  const lineGeo = new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(), new THREE.Vector3(), end.clone()]);
  const line = new THREE.Line(lineGeo, new THREE.LineBasicMaterial({ color: INK, transparent: true, depthTest: false, depthWrite: false }));
  [ring, ping, core, line].forEach((o) => { o.renderOrder = 10; g.add(o); });
  plane.add(g);

  const el = document.createElement('button');
  el.type = 'button';
  el.className = 'tag' + (l.off[0] < 0 ? ' left' : '');
  el.setAttribute('aria-label', `${l.name}, details`);
  el.innerHTML = `<span class="tag-k">${l.kicker}</span><span class="tag-row"><span class="tag-n">${l.idx}</span><span class="tag-t">${l.name}</span></span>`;
  el.addEventListener('click', () => openDrawer(l));
  el.addEventListener('mouseenter', () => { hotId = l.id; });
  el.addEventListener('mouseleave', () => { if (hotId === l.id) hotId = null; });
  tagLayer.appendChild(el);

  Object.assign(l, { g, ring, ping, core, line, end, el, alpha: 0, compact: null, w: 0, h: 0 });
});

/* ------------------------------------------------------------------ Scroll → frame mapping */
const sections = $$('main > section');
const chapterEls = sections.filter((s) => s.classList.contains('chapter'));
let boxes = [];
function layoutSections() {
  chapterEls.forEach((s) => {
    const span = +s.dataset.f1 - +s.dataset.f0;
    s.style.height = `${Math.max(200, span * (mqMobile.matches ? 4.2 : 3.6))}vh`;
  });
  boxes = sections.map((s) => ({ s, top: s.offsetTop, h: s.offsetHeight, f0: +s.dataset.f0, f1: +s.dataset.f1, ch: +(s.dataset.ch || 0) }));
}
function frameForScroll(y) {
  for (const b of boxes) if (y < b.top + b.h) return b.f0 + clamp((y - b.top) / b.h, 0, 1) * (b.f1 - b.f0);
  return FRAME_COUNT - 1;
}
const boxAt = (y) => boxes.find((b) => y < b.top + b.h) || boxes[boxes.length - 1];
function scrollForFrame(f, ch) {
  const b = boxes.find((x) => x.ch === ch && f >= x.f0 && f <= x.f1) || boxes.find((x) => x.ch && f >= x.f0 && f <= x.f1);
  return b ? b.top + ((f - b.f0) / (b.f1 - b.f0)) * b.h + 2 : 0;
}

let lenis = null;
function scrollToY(y) {
  if (lenis) lenis.scrollTo(y, { duration: 1.8 });
  else window.scrollTo(0, y);
}
function goToLabel(l) {
  scrollToY(scrollForFrame(l.jump, l.jump > 125 ? 3 : l.chapter));
  setTimeout(() => { hotId = l.id; setTimeout(() => { if (hotId === l.id) hotId = null; }, 2400); }, 1600);
}

/* ------------------------------------------------------------------ UI */
const drawer = $('#drawer');
let openLabel = null;
let hotId = null;
function openDrawer(l) {
  openLabel = l;
  $('#d-num').textContent = `${l.idx} / 09`;
  $('#d-title').textContent = l.name;
  $('#d-kicker').textContent = l.kicker;
  $('#d-desc').textContent = l.desc;
  $('#d-flow').textContent = l.flow;
  $('#d-specs').innerHTML = l.specs.map(([k, v]) => `<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');
  drawer.classList.add('open');
  drawer.setAttribute('aria-hidden', 'false');
  closeIndex();
}
function closeDrawer() {
  openLabel = null;
  drawer.classList.remove('open');
  drawer.setAttribute('aria-hidden', 'true');
}
$('#drawer-close').addEventListener('click', closeDrawer);

const indexPanel = $('#index-panel');
const indexBtn = $('#index-btn');
function closeIndex() { indexPanel.hidden = true; indexBtn.setAttribute('aria-expanded', 'false'); }
indexBtn.addEventListener('click', () => {
  const open = indexPanel.hidden;
  indexPanel.hidden = !open;
  indexBtn.setAttribute('aria-expanded', String(open));
});
$('#index-list').innerHTML = LABELS.map((l) => `<li><button data-id="${l.id}"><span>${l.idx}</span><span>${l.name}</span></button></li>`).join('');
$('#index-list').addEventListener('click', (e) => {
  const b = e.target.closest('button[data-id]');
  if (!b) return;
  closeIndex();
  goToLabel(byId(b.dataset.id));
});

$$('.ch-list').forEach((ul) => {
  ul.innerHTML = ul.dataset.tags.split(' ').map((id) => {
    const l = byId(id);
    return `<li><button data-id="${id}"><span class="n">${l.idx}</span><span>${l.name}</span><span class="arrow">Details</span></button></li>`;
  }).join('');
  ul.addEventListener('click', (e) => { const b = e.target.closest('button'); if (b) openDrawer(byId(b.dataset.id)); });
  ul.addEventListener('mouseover', (e) => { const b = e.target.closest('button'); if (b) hotId = b.dataset.id; });
  ul.addEventListener('mouseleave', () => { hotId = null; });
});

$('#outro-list').innerHTML = LABELS.map((l) => `<li><button data-id="${l.id}"><span class="n">${l.idx}</span><span><span class="t">${l.name}</span><span class="k">${l.kicker}</span></span></button></li>`).join('');
$('#outro-list').addEventListener('click', (e) => { const b = e.target.closest('button'); if (b) openDrawer(byId(b.dataset.id)); });
$('#replay').addEventListener('click', () => scrollToY(0));
$$('[data-go]').forEach((b) => b.addEventListener('click', () => {
  const box = boxes.find((x) => x.ch === +b.dataset.go);
  if (box) scrollToY(box.top + 2);
}));
addEventListener('keydown', (e) => { if (e.key === 'Escape') { closeDrawer(); closeIndex(); } });

const mouse = { nx: 0, ny: 0 };
addEventListener('pointermove', (e) => {
  mouse.nx = (e.clientX / innerWidth) * 2 - 1;
  mouse.ny = (e.clientY / innerHeight) * 2 - 1;
});

/* ------------------------------------------------------------------ Scroll choreography */
function setupScrollAnimations() {
  const split = (el, type = 'lines') => SplitText.create(el, { type, mask: 'lines', linesClass: 'line' });

  // Hero: title rises in letter by letter, then drifts up and out as you scroll
  const title = split('.hero-title', 'chars,lines');
  const heroCopy = split('.hero-meta, .hero-lede');
  if (reduced) return;
  gsap.timeline({ delay: 0.25 })
    .from(title.chars, { yPercent: 105, duration: 1.5, ease: 'expo.out', stagger: 0.045 })
    .from(heroCopy.lines, { yPercent: 105, duration: 1.1, ease: 'expo.out', stagger: 0.06 }, 0.45)
    .from('.scroll-hint', { opacity: 0, duration: 1 }, 0.9);
  gsap.to('.hero-title', { yPercent: -45, ease: 'none', scrollTrigger: { trigger: '.hero', start: 'top top', end: 'bottom top', scrub: true } });
  gsap.to('.hero-meta, .hero-lede, .scroll-hint', { opacity: 0, y: -30, ease: 'none', scrollTrigger: { trigger: '.hero', start: 'top top', end: '45% top', scrub: true } });

  // Chapters: heading and body lines unmask on entry, reverse on exit; progress rule is scrubbed
  chapterEls.forEach((sec) => {
    const h = split(sec.querySelector('h2'));
    const body = split(sec.querySelector('.ch-body'));
    const tl = gsap.timeline({ paused: true })
      .from(sec.querySelector('.ch-index'), { opacity: 0, y: 10, duration: 0.6, ease: 'power2.out' })
      .from(h.lines, { yPercent: 110, duration: 1.1, ease: 'expo.out', stagger: 0.08 }, 0.05)
      .from(body.lines, { yPercent: 110, duration: 1, ease: 'expo.out', stagger: 0.035 }, 0.2)
      .from(sec.querySelectorAll('.ch-list li'), { opacity: 0, y: 14, duration: 0.7, ease: 'power3.out', stagger: 0.06 }, 0.45)
      .from(sec.querySelector('.ch-progress'), { scaleX: 0, transformOrigin: 'left', duration: 0.9, ease: 'expo.out' }, 0.5);
    ScrollTrigger.create({
      trigger: sec, start: 'top 55%', end: 'bottom 45%',
      onToggle: (self) => (self.isActive ? tl.timeScale(1).play() : tl.timeScale(2.2).reverse()),
    });
    gsap.to(sec.querySelector('.ch-progress i'), { scaleX: 1, ease: 'none', scrollTrigger: { trigger: sec, start: 'top top', end: 'bottom bottom', scrub: true } });
  });

  // Outro
  const outroTitle = split('.outro-title');
  gsap.timeline({ scrollTrigger: { trigger: '.outro', start: 'top 60%', toggleActions: 'play none none reverse' } })
    .from(outroTitle.lines, { yPercent: 110, duration: 1.2, ease: 'expo.out', stagger: 0.08 })
    .from('.outro .ch-index', { opacity: 0, duration: 0.6 }, 0)
    .from('.outro-list li', { opacity: 0, y: 24, duration: 0.8, ease: 'power3.out', stagger: 0.05 }, 0.25)
    .from('#replay', { opacity: 0, duration: 0.6 }, 0.7);
}

/* ------------------------------------------------------------------ Resize */
function fit() {
  const a = innerWidth / innerHeight;
  camera.aspect = a;
  const t = Math.tan(THREE.MathUtils.degToRad(camera.fov / 2));
  baseDist = Math.min(PH, PW / a) / 1.14 / (2 * t);
  camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
  layoutSections();
  LABELS.forEach((l) => { l.w = 0; });
}
addEventListener('resize', () => { fit(); ScrollTrigger.refresh(); });

/* ------------------------------------------------------------------ Render loop */
let tracks = null;
let frameF = 0, shownIdx = -1, vel = 0, introStart = 0, lastCh = -1;
const tilt = { x: 0, y: 0 };
const v3 = new THREE.Vector3();
const frameN = $('#frame-n');
const progressFill = $('#progress-fill');
const navBtns = $$('[data-go]');
const easeOut = (t) => 1 - Math.pow(1 - t, 4);

function trackAt(id, f) {
  const t = tracks[id];
  const i = Math.floor(f), j = Math.min(i + 1, FRAME_COUNT - 1), k = f - i;
  const a = t[i], b = t[j];
  if (!a && !b) return null;
  if (!a) return k > 0.5 ? b : null;
  if (!b) return k < 0.5 ? a : null;
  return [a[0] + (b[0] - a[0]) * k, a[1] + (b[1] - a[1]) * k];
}

function tick(now) {
  requestAnimationFrame(tick);
  const W = innerWidth, H = innerHeight, y = scrollY;
  const time = now / 1000;

  const targetF = frameForScroll(y);
  frameF = reduced ? targetF : lerp(frameF, targetF, 0.18);
  if (Math.abs(frameF - targetF) < 0.002) frameF = targetF;
  const idx = clamp(Math.round(frameF), 0, FRAME_COUNT - 1);
  if (idx !== shownIdx && images[idx]) {
    frameTex.image = images[idx];
    frameTex.needsUpdate = true;
    shownIdx = idx;
  }
  vel = lerp(vel, clamp(Math.abs(targetF - frameF) / 10, 0, 1), 0.1);

  const box = boxAt(y + H * 0.5);
  const ch = box.ch;
  const inOutro = box.s.classList.contains('outro');
  if (ch !== lastCh) {
    lastCh = ch;
    document.body.classList.toggle('in-chapter', !!ch);
    navBtns.forEach((b) => b.classList.toggle('on', +b.dataset.go === ch));
  }

  const intro = introStart ? (reduced ? 1 : easeOut(clamp((now - introStart) / 2400, 0, 1))) : 0;
  const heroP = clamp(y / H, 0, 1);

  tilt.x = lerp(tilt.x, mouse.ny * 0.04, 0.05);
  tilt.y = lerp(tilt.y, mouse.nx * 0.07, 0.05);
  rig.rotation.set(tilt.x, tilt.y, 0);
  // Intro pulls back from a close crop; scrolling out of the hero eases slightly closer
  const zoom = 1 - (1 - intro) * 0.12 - heroP * 0.035;
  camera.position.set(-tilt.y * 1.1, tilt.x * 0.7, baseDist * zoom - vel * 0.4);
  camera.lookAt(0, 0, 0);

  planeMat.uniforms.uVel.value = vel;
  planeMat.uniforms.uFade.value = intro;
  planeMat.uniforms.uDim.value = lerp(planeMat.uniforms.uDim.value, inOutro ? 1 : 0, 0.05);
  scene.updateMatrixWorld();

  if (tracks) {
    const mobile = mqMobile.matches;
    // Callouts that would sit on top of the chapter copy are hidden
    const copy = ch && !mobile ? box.s.querySelector('.ch-text').getBoundingClientRect() : null;
    const measure = [];
    // Pass 1: place every trackable marker and project its callout end point
    for (const l of LABELS) {
      const primary = l.chapter === ch || (l.also || []).includes(ch);
      const p = ch && !inOutro && (!mobile || primary) ? trackAt(l.id, frameF) : null;
      l.live = !!p && p[0] > 0.02 && p[0] < 0.98 && p[1] > 0.04 && p[1] < 0.96;
      if (!l.live) continue;
      const px = (p[0] - 0.5) * PW, py = (0.5 - p[1]) * PH;
      l.g.position.set(px, py, curveZ(px) + 0.01);

      const hot = hotId === l.id || openLabel === l;
      const compact = !primary && !hot;
      if (compact !== l.compact) { l.compact = compact; l.el.classList.toggle('compact', compact); l.w = 0; }
      l.el.classList.toggle('hot', hot);
      l.hot = hot;

      const s = mobile ? 0.6 : compact ? 0.8 : 1;
      l.end.set(l.off[0] * s, l.off[1] * s, l.off[2] * s);
      const pos = l.line.geometry.attributes.position;
      pos.setXYZ(1, l.end.x * 0.12, l.end.y, l.end.z * 0.6);
      pos.setXYZ(2, l.end.x, l.end.y, l.end.z);
      pos.needsUpdate = true;

      l.g.updateMatrixWorld();
      v3.set(0, 0, 0);
      l.g.localToWorld(v3).project(camera);
      l.ax = (v3.x * 0.5 + 0.5) * W;
      l.ay = (-v3.y * 0.5 + 0.5) * H;
      v3.copy(l.end);
      l.g.localToWorld(v3).project(camera);
      l.sx = (v3.x * 0.5 + 0.5) * W;
      l.sy = (-v3.y * 0.5 + 0.5) * H;
      if (!l.w) measure.push(l);
    }
    for (const l of measure) { l.w = l.el.offsetWidth; l.h = l.el.offsetHeight; }

    // Pass 2: resolve screen boxes, hide anything that collides with the chapter copy or an
    // earlier callout (primary callouts claim space first), then fade
    const placed = [];
    const order = [...LABELS].sort((a, b) => (a.compact === b.compact ? 0 : a.compact ? 1 : -1));
    for (const l of order) {
      let want = 0;
      if (l.live) {
        const left = l.off[0] < 0;
        l.x = clamp(left ? l.sx - l.w : l.sx, 12, W - l.w - 12);
        l.y = clamp(l.sy - l.h, 84, H - l.h - 50);
        const hit = (x0, y0, x1, y1) => copy && x0 < copy.right + 20 && x1 > copy.left - 20 && y0 < copy.bottom + 20 && y1 > copy.top - 20;
        const clash = placed.some((o) => l.x < o.x + o.w + 8 && l.x + l.w + 8 > o.x && l.y < o.y + o.h + 4 && l.y + l.h + 4 > o.y);
        want = clash || hit(l.x, l.y, l.x + l.w, l.y + l.h) || hit(l.ax - 12, l.ay - 12, l.ax + 12, l.ay + 12) ? 0 : 1;
        if (want) placed.push(l);
      }
      l.alpha = lerp(l.alpha, want * intro, want ? 0.12 : 0.25);
      const on = l.alpha > 0.01 && l.live;
      l.g.visible = on;
      l.el.style.visibility = on ? 'visible' : 'hidden';
      if (!on) continue;

      const pulse = (time * 0.6 + +l.idx * 0.17) % 1;
      const base = l.hot ? 1.6 : l.compact ? 0.75 : 1.1;
      l.ring.scale.setScalar(base);
      l.ping.scale.setScalar(base * (1 + pulse * 2));
      l.ping.material.opacity = l.alpha * (1 - pulse) * 0.6;
      l.ring.material.opacity = l.alpha;
      l.core.material.opacity = l.alpha;
      l.line.material.opacity = l.alpha * (l.compact ? 0.4 : 0.75);

      const rise = (1 - l.alpha) * 10;
      l.el.style.transform = `translate3d(${l.x.toFixed(1)}px, ${(l.y + rise).toFixed(1)}px, 0)`;
      l.el.style.opacity = l.alpha.toFixed(3);
      l.el.style.setProperty('--a', l.alpha.toFixed(3));
    }
  }

  frameN.textContent = String(idx).padStart(3, '0');
  const max = document.documentElement.scrollHeight - H;
  progressFill.style.transform = `scaleX(${clamp(y / max, 0, 1)})`;

  renderer.render(scene, camera);
}

/* ------------------------------------------------------------------ Boot */
history.scrollRestoration = 'manual';
window.scrollTo(0, 0);
fit();
requestAnimationFrame(tick);

Promise.all([
  fetch('data/tracks.json').then((r) => r.json()),
  loadAll(),
  document.fonts.ready,
]).then(([data]) => {
  tracks = {};
  for (const [k, v] of Object.entries(data.tracks)) tracks[k] = smoothTrack(v);
  frameTex.image = images[0];
  frameTex.needsUpdate = true;
  shownIdx = 0;

  $('#loader').classList.add('done');
  document.body.classList.remove('loading');
  layoutSections();

  if (!reduced) {
    lenis = new Lenis({ lerp: 0.085, wheelMultiplier: 0.9 });
    lenis.on('scroll', ScrollTrigger.update);
    gsap.ticker.add((t) => lenis.raf(t * 1000));
    gsap.ticker.lagSmoothing(0);
  }
  setupScrollAnimations();
  ScrollTrigger.refresh();
  introStart = performance.now();
});
